cp .ideavimrc ~/_ideavimrc
cp bbzero/plugins.rc "c:/bbZero/plugins.rc"
cp bbzero/menu.rc "c:/bbZero/menu.rc"
cp bbzero/blackbox.rc "c:/bbZero/blackbox.rc"
cp bbzero/BlackboxBar.rc "c:/bbZero/plugins/BlackboxBar/BlackboxBar.rc"
cp bbzero/bbLeanSkin.rc "c:/bbZero/plugins/bbLeanSkin/bbLeanSkin.rc"
cp bbzero/exclusions.rc "c:/bbZero/plugins/bbLeanSkin/exclusions.rc"
cp bbzero/bbLeanSkinMenu.rc "c:/bbZero/plugins/bbLeanSkin/bbLeanSkinMenu.rc"
cp keyrate.bat ../keyrate.bat
